# Generated by Django 4.2.9 on 2024-01-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_passwordHash', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worlds',
            fields=[
                ('world_id', models.AutoField(primary_key=True, serialize=False)),
                ('world_name', models.CharField(max_length=20, null=True)),
                ('pin', models.CharField(max_length=4, null=True)),
                ('created', models.DateField(null=True)),
                ('updated', models.DateField(null=True)),
                ('last_played', models.DateField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameapp.users')),
            ],
        ),
    ]
