# Generated by Django 4.2.9 on 2024-01-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_passwordHash',
            new_name='user_pass_hash',
        ),
    ]
